name: medoc19
description: A new Flutter application.
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.2.0+2

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^0.4.0
  zoomable_image: ^1.2.1+1
  flutter_launcher_icons: ^0.7.0
  shared_preferences: ^0.5.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  http: ^0.12.0
  cupertino_icons: ^0.1.2
  random_pk: any
  dio: any
  path_provider: any
  flutter_webview_plugin: ^0.3.0+2
  url_launcher: ^5.0.1
  
flutter_icons:
  image_path: "assets/pics/app_lunch.png" 
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/pics/dell.png
    - assets/pics/hp.png
    - assets/pics/huawei.png
    - assets/pics/mi.webp
    - assets/pics/floor.png
    - assets/pics/location_icon.png
    - assets/login_background.png
    - assets/pics/x_icon.png
    - assets/pics/app_lunch.png
    #agenda
    - assets/pics/dinner.png
    - assets/pics/door.png
    - assets/pics/event.png
    - assets/pics/pattern.png
    - assets/pics/time.png
      #speakers
    - assets/pics/dr_saud_alsifri.png
    - assets/pics/jean_claude_mbanya.png
    - assets/pics/paolo_pozaili.png
    - assets/pics/prof_abdulrahman_alsheikh.png
    - assets/pics/raffaella_buzzetti.png
    - assets/pics/ralph_anthony_defronzo.png

    #INFORMATION
    - assets/pics/circlelogob.png
    - assets/pics/facebook.png
    - assets/pics/gsk.png
    - assets/pics/instagram.png
    - assets/pics/logob.png
    - assets/pics/sanofi.png
    - assets/pics/twitter.gif
    #ABOUT
    - assets/pics/about_background.png
    - assets/pics/logow.png
    - assets/pics/move_backgrounf.png
    - assets/pics/move.png
    - assets/pics/personb.png
    - assets/pics/logo.png

    

    

    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
